#:schema node_modules/wrangler/config-schema.json
name = "boristanedotcom-worker"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-02-11"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

routes = [
  { pattern = "boristane.com", custom_domain = true },
]

[observability]
enabled = true
